spring:
  application:
    name: denizbank-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: buysell
  datasource:
    url: jdbc:postgresql://postgres:5432/buysell
    username: admin
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

---

spring:
  profiles: localhost
  jpa:
    properties:
      hibernate:
        default_schema: buysell
  datasource:
    url: jdbc:postgresql://localhost:5433/buysell
    username: admin
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        default_schema: buysell
  d
