spring:
  application:
    name: zuul-edge-server

server:
  port: 8765

zuul:
  routes:
    denizbank-service:
      path: /api/1.0/denizbank/**
      service-id: denizbank-service
      strip-prefix: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

---

spring:
  profiles: localhost

server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
